server:
  tomcat.threads.max: 200
  port: 8080

spring:
#  thymeleaf:
#    check-template-location: false #выкл. темплейты для web-страниц(40X, 50X и т.п.)
  application:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/polls_system_db?currentSchema=public
    username: admin
    password: admin
    hikari:
      connectionTimeout: 60000
      idleTimeout: 60000
      maxLifetime: 300000
      minimumIdle: 5
      maximumPoolSize: 10
  sql.init.encoding: UTF-8

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: error
    ru.pstu.poll_system_service: error


token:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351